name: CPP CI Pipeline

on: [push]

env:
  DOCKER_IMAGE_NAME: ""
  PROJECT_DIR: "."
  BUILD_SYSTEM: "Ninja"
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Custom Build CI action
      uses: ./.github/actions/build
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gitleaks_token: ${{ secrets.GITLEAKS_TOKEN }}
        source_dir:  ${{ env.PROJECT_DIR }}
        build_system: ${{env.BUILD_SYSTEM}}

    - name: Test Dockerfile 
      uses: ./.github/actions/test
      with:
        docker_repo_name: ${{ env.DOCKER_IMAGE_NAME || github.event.repository.name }}

    - name: Deploy Dockerfile 
      if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
      uses: ./.github/actions/test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        docker_repo_name: ${{ env.DOCKER_IMAGE_NAME || github.event.repository.name }}